
var Twit = require('twit');
var TwitterBot = require('node-twitterbot').TwitterBot;
var Bot = new TwitterBot({
 consumer_key: process.env.BOT_CONSUMER_KEY,
 consumer_secret: process.env.BOT_CONSUMER_SECRET,
 access_token: process.env.BOT_ACCESS_TOKEN,
 access_token_secret: process.env.BOT_ACCESS_TOKEN_SECRET
});


var phraseArray = [ 
"The murder came and sat on my shoulders",
"and called me brother",
"It was small and heavy",
"It was talkative",
"It went by my friend's name",
"I wondered if my friend had become",
"his own murder",
"present in his absence",
"a hand erasing itself",
"I hunched under the weight",
"older than me",
"I recognized others",
"the hunched and shuffling step",
"I called them my friends",
"fellow travelers bearing the dark",
"across the deep",
"We became",
"the silent tribe of undead",
"scarved in names",
"shadowy chatter",
"rubbed our necks raw",
"burnished our shoulders",
"long pale planes",
"inch by inch",
"year by year",
"This year",
"I realized the murder had grown",
"soft around the edges",
"indistinct in its face",
"and my friend",
"who was once a video shock",
"in my memory",
"had become broad strokes",
"on wet paper",
"it grew lighter as it spoke",
"a song that had to be breathed into me",
"and soon it would fall silent and crouch",
"on my shoulders like a tired child",
"Now I grow light",
"and miss the weight",
"I say to it",
"stay heavy",
"Who could love like I do",
"The ones who raised me read the air as gospel",
"faces lifted",
"dark nostrils flaring",
"they apprehended",
"rabbits in the grass and the grass itself",
"its many",
"tiny cities of movement",
"This was before names",
"when I knew my kind by smell",
"when the dirt",
"in my hair was a crown and the borders of the world",
"were drawn by flies",
"My mothers were great",
"hunters",
"I can still feel them returning at dawn",
"faces furred with mist",
"jaws darkened with berries",
"bloodied with mice",
"Rabbits were better",
"the kidney-tang",
"the meat between ribs tough and sweet",
"but mice were common",
"a breakfast of tiny bones",
"between your teeth",
"Sometimes I’d follow them out",
"the blackberry patch",
"prowl deep",
"into its nuzzle of thorns",
"and steal its sugar",
"by mouthfuls",
"Once they came back",
"with two chickens",
"necks snapped",
"warm to the touch",
"I’ll never forget the grass-rich",
"gizzard",
"the pink flesh delicate and supple",
"the men who came with smoke and cages",
"looking for their stolen birds",
"They carried me",
"away",
"scrubbed the woods from my face",
"dressed me",
"in false furs",
"and gave me a name",
"I fought hard",
"refused the dead food",
"barked stubbornly against",
"the shut doors and money-scented rooms",
"But in time",
"jazz and fresh bread",
"the mysteries of motion",
"I learned",
"the names of planets",
"marveled at the forces",
"dressed myself in spun fur",
"and walked upright in the peopled world",
"What hunted me",
"I learned to love", 
"what trapped me",
"I called a home",
"Now my mothers are there",
"when I can’t sleep",
"and smell the woods",
"the tart must",
"trampled sorrel",
"ripening in the dark",
"I hear them",
"at the yard’s edge",
"in the tall grass",
"lost breath and eyeshine",
"slicked with moonlight",
"manifold and ghostly",
"Then came the war of God and heavy metal",
"We grew our hair",
"We shaved our heads",
"We cut the sleeves off shirts and smoked",
"in the dark",
"our heavy boots like big black hammers",
"Our fathers went to bed with sore hands",
"and we stayed up with sore faces",
"We crept out windows",
"and slipped into cars",
"the moon a white wafer",
"laying light like snow across the road",
"We drove",
"past the high school and the fire station",
"past gas stations and strip malls drenched",
"in sodium light",
"We passed the half-made houses",
"clefts in the earth veiled in concrete",
"The crossroad",
"towns and their general stores",
"ghost ships",
"marooned in the fog",
"We drove",
"with the windows down and the music so loud",
"the floorboard growled",
"our bodies rumbled",
"in the thump",
"drums pulsing in the windshield",
"On that forever night",
"electric to the pore",
"we were princes of on-ramps",
"soon to drive",
"into cities whose hearts we would hold in our hands",
"The body’s corporeal fire",
"the children",
"who lived in us",
"the wonders that would smite us",
"were winter lightning",
"dazzling and absurd",
"We could barely imagine the sun",
"eating into our rooms",
"the residue",
"of the night diminished",
"our mothers",
"crossing themselves in the kitchen",
"our fathers waiting by our open windows",
"their faces clear and sharp as a crucifix",
"You’re awake now because the rain is green pennies",
"clattering the window",
"and you imagined a girl",
"You open your eyes to livid light",
"the perpetual",
"blue hour of a wet winter",
"and you know",
"that if you lifted the blind",
"you’d see her there",
"in her blue dress",
"cigarette behind her ear",
"waiting for you to come down and pick out a tape",
"for the dark wander down gravel roads",
"and through the lonely towns",
"Those roads",
"and the towns walled in",
"by houses that went from rebar to palace",
"in the flash of thirty years",
"You try to rise",
"climb out the window",
"and leap down to the yard",
"where you might run your hands along the wet",
"cotton of her hips",
"but the leopard that lived",
"inside you has long left to find the night fires",
"of the young",
"They’re dozing just now",
"the night-fire revelers",
"the leopard-possessed",
"their lean wavering bodies slicked and glutted",
"old smoke in their perfect hair",
"She’s out there",
"soaked to her ghost bones",
"trying to draw",
"you back with her fistfuls of pennies and rain",
"but the alarm is four minutes away",
"and all over the neighborhood",
"dogs",
"greeting the first timid flush of sun",
"You hold her name close on your tongue",
"like an old song",
"a memory of something",
"hard and sweet",
"and through the blinds",
"you say",
"Go",
"You can believe it on a day like this",
"when the red-black tree refuses to bloom",
"and rain presses at the window",
"turning",
"by degrees to snow",
"Here between sessions",
"of sleep and code",
"where nothing loads and all",
"screens are waterfalls of error",
"you lean",
"into this stack of numbers and faces",
"signs",
"of the old world",
"and feel the carbonated",
"velvet of the static field",
"the crinkle",
"and hush around your lips",
"the fine hairs rising",
"on your cheeks",
"Here between skin and screen",
"everything is pixelated snow",
"all this light",
"the elegant errors rising",
"falling in sleep",
"all this is grass",
"It could be China",
"or the moon",
"it looks like familiar earth",
"this finger of sand and wood",
"we might call home",
"Everyone lies in the brine dark",
"and dreams of roast beef the way we used to think of breasts",
"soft",
"warm",
"pink",
"supple on the tongue",
"but we’re here now",
"a second world",
"scurvied",
"bitten",
"boiling with the fish of fever",
"the season of sea-rock",
"and hull-creak brought to sudden gravity",
"the halt",
"at shore",
"Sand and shell",
"a few trees",
"needling scrub",
"muscle-colored berries that look",
"like poison",
"something sweet",
"we all agree that this was a terrible idea",
"Little creeks of flu sweat tickling our scalps",
"tongues gnawed raw",
"by salt water",
"salt beef and bitter dread",
"and nowhere to lay our heads",
"We hunch against the wind and become",
"its absence",
"the rock around which it howls",
"We move",
"into woods",
"each step labored",
"dragging behind us",
"cities and children of industry",
"highways and the coarse machines",
"that will trample them",
"sciences and wonders",
"and many nights",
"of long knives",
"Let’s turn back",
"someone says",
"and we nearly do",
"but then they appear",
"three or four",
"at a distance",
"carrying fish and fruit",
"Years from now",
"when no one can remember what they brought us",
"when their faces are just the smeared sketch of memory",
"when we have quartered the land into our English boxes",
"and the old words and tongues that spoke them",
"gone as the boats that bore us",
"we will recall this meeting of our tribes",
"one going home",
"the other searching",
"and how at first they looked like gods to us",
"like masters",
"of the strange and terrible land",
"and we thought",
"maybe these are our brothers",
"maybe they can save us",
"But first the data",
"swatches of lightning",
"unruly in the network",
"First the servers",
"calling out across a universe of cable",
"like night birds",
"The circus of taxonomies",
"orphaned sparks of text and sign",
"filling up the little squares of fire in our pockets",
"First the work that won’t sleep",
"sleep",
"that won’t come",
"and meeting after meeting",
"to map the riot of packets that follow us",
"luminous",
"across the void",
"When will I go out",
"forget",
"the language of my trade",
"close my eyes",
"and listen to the sparrows call me back",
"You do not know winter as we know winter",
"You do not love hands as we love hands",
"You cannot sleep",
"nor wish to be",
"the subject of memory",
"the object",
"of secret fever",
"You cannot forget",
"nor wish to forget",
"Therefore",
"until you are one of our tribe",
"we keep your fevers for you",
"We hold in our mouths the grace",
"of forgetting",
"until you are ready",
"to come to memory’s end",
"That is when",
"winter will settle into your shoulders",
"numb sleep",
"error’s culmination",
"the cold eye giving up its zeroes to the void",
"The books and magazines",
"The suits",
"shirts",
"jeans",
"The laughable junkyard of shoes",
"The space underbed",
"the landscape",
"of fur and dimes",
"The nightstand drawer - condoms",
"coins",
"pens",
"a postcard from Maui",
"The cream-colored sheets",
"The mattress with its faded wine stain",
"The skeleton of the bed",
"The planks",
"The intricate headboard",
"with a sheen of dust",
"The footboard you hated",
"The ocean-colored rug we bought from",
"that women who loved everyone",
"The dresser my neighbor abandoned",
"The hangers",
"tangled on the floor",
"like ruins",
"The room where you slept",
"after I told you",
"The shower curtain",
"The mysteries undersink",
"The box of tools",
"The bottomless bag of screws",
"The couch",
"The bones of the couch",
"The plates",
"wrapped in the newspapers",
"I started gathering when I knew",
"The silverware in a single freezer bag",
"The coats",
"The broom and mop",
"The sleeping bag and the empty bottles",
"The bones in my chest",
"The moving truck",
"and the procession",
"The house revealing itself",
"box by box",
"The things abandoned",
"The walkthrough",
"with its many",
"resident shadows",
"The shadow of you in that room",
"The shadow of the cat",
"The shadow of the bed",
"The keys laid out like coins in a well",
"The street laid out in two directions",
"The shadow of you in the window",
"The rain",
"The lifeboat",
"The bucket of tears",
"The dawn",
"The shore",
"reborn as bullfrogs",
"calling from the reeds",
"to speak of flies",
"Here in Philadelphia",
"the disappeared move",
"as black ants in unseen lines",
"in the grooves between stones",
"Everywhere you go",
"footsteps follow you that aren't",
"your own",
"and when you turn",
"you taste ashes",
"ashes of a field or a braid",
"of hair",
"ashes of a house",
"that held you in your last life",
"Pity your body its tether",
"of shadow",
"Pity your shadow",
"its shackle of light",
"Some lose theirs to sickness",
"war",
"a sudden accident",
"the bike with bad brakes",
"the microbe crashing through",
"the body's grove",
"We lost ours to fear and aspiration",
"eyes warm and voices low",
"told us how",
"the body would let her go with just a scratch and a nudge",
"This was the moment we came of age",
"After",
"there were no flowers and no shadows in which to hide",
"my face",
"and nothing lived between us but the shape",
"of someone gone",
"The last bed we shared",
"not even wet with tears",
"We were hobbled",
"and humbled",
"years waiting for us like two roads",
"cut in hard earth",
"leading far and away",
"The ones I miss the most I rolled by hand",
"packed with moss and damp earth",
"The paper",
"crackled quietly between my fingers",
"as I packed down all those fields",
"the leaves",
"of Kentucky and Virginia",
"The moment",
"it turned to chocolate gravel in the floor",
"of my throat",
"everything became",
"easy",
"lying in bed with our twin coils",
"of smoke rising in the streetlight",
"standing in the shower with one dry hand",
"driving on a winter morning",
"one hand on the wheel",
"tipping the cigarette out the window",
"I remember",
"the car charged down the freeway",
"marveling at the rain of sparks",
"as if this were some sort of bona fide magic",
"a true slice of the mysterious held between my fingers",
"drawn into my body",
"where it might grow",
"The last one was on a bench in early spring",
"forgettable except for being the last",
"its smell",
"rich as the scent of a woman’s hair",
"In bed that night",
"I mourned it",
"fingers to my face",
"as it faded away",
"Goodbye my slightly deadly",
"goodbye my nearly precious",
"Here she is again",
"soft-eyed",
"smiling",
"younger",
"than you remember",
"Up from a riverbed",
"or a forest floor",
"or some darkness",
"you dreamt of all these years",
"where your light lived",
"waiting for her like a beacon",
"You want to wrap around her",
"and purr and purr",
"like the lost thing you are",
"but she is really just",
"light and shadow",
"the distance",
"between you and the moment",
"she became was",
"You say to her",
"Why",
"I left this hat",
"and I really love it",
"I need it for where I'm going",
"You take her to the hat",
"because you love her like",
"you love the roots of your teeth",
"and the long wet wings of lung",
"that keep you in this world",
"the hat is on her",
"just a suggestion",
"of feathers",
"you open the door",
"And there",
"she goes",
"with purpose",
"and direction",
"exactly as you",
"imagined her in those years",
"you wanted",
"the mothered",
"years",
"the mothering years",
"where she might have been",
"a sliver of light or a pane",
"of green water or anything",
"but this feathered shadow",
"to which you say",
"Dress warm",
"say your prayers",
"don’t be late",
"As you make your way to that border kingdom",
"where the bearded god and the elephant god",
"sitting down to shuffle cards",
"a breeze that smells of funnel cake",
"ever so slightly",
"To your left",
"in a field between two palms",
"you'll see",
"the carnival of ancestors erupt like the first blush",
"of garlic in early summer",
"At this point",
"be light",
"The gods will keep playing",
"and those ancient troublemakers",
"winnowed",
"by the long party of the afterlife",
"will always be",
"the noise between heartbeats",
"the noise of space",
"Whatever happens now",
"remember how she cried",
"when she was new",
"and how she felt when you held her - ",
"the negative weight",
"the serious laughter",
"You're on the beach again",
"the lonely blue before dawn",
"is everywhere",
"and Black Rock is still dark",
"Your father is here",
"smiling",
"younger than you remember",
"his auburn beard starred with brine",
"You crouch by a pit of coals",
"warming a pot of water",
"and all at once",
"the salt wind is full of coffee steam",
"You sit together",
"not speaking",
"holding cups in both hands",
"watching the water",
"take on its lucid blue",
"When you look at your father",
"stare out at the cloud horizon",
"watch him and carry him",
"and make for him a place inside you to speak for him",
"he is once again old enough to speak for himself",
"his loneliness is gone as lightning",
"The sun emerges from the mountain",
"and the grains of sand on your father's leg",
"light up one by one",
"like tiny blonde stars",
"He breaks into a smile",
"and you turn to see",
"what he's grinning about",
"Just now",
"the sea floor",
"catches gentle fire",
"your mother rises from the waves",
"she is younger than you",
"younger than you ever knew she could be",
"her hair to her waist",
"her eyes",
"miniature islands",
"her body a supple flame",
"lean",
"strong",
"golden",
"whole",
"Little mesh of lightning",
"lattice of cold fire",
"streaming through the ether",
"like bees or moonlight",
"may you be a faithful",
"keeper of voices",
"Before I snuff out the screen",
"and return to my body's subtler engine",
"before I step out of the cloud",
"into which my night has fallen",
"let me pause to bless you",
"consequence of gears",
"heir to counting stones",
"keeper of the songs I make",
"keeper of the songs I sing",
"For the soft flesh of my inner cheeks",
"For the furious muscle of my tongue and its many imperfect languages",
"For the plastic ribs of my throat",
"and that vibrant reed where my voice lives",
"For the cartilage of that shoulder that has come again and again out of joint",
"For the lungs I filled with twenty years of smoke",
"For the heart-side ribs I broke in a fight",
"For the liver-side ribs I broke in a drunken carouse",
"we were celebrating too hard",
"and I fell",
"and the bar stool caught me",
"For the stomach that burns and pangs with acids and worry",
"For the pancreas that lives there silently",
"that may have hurt me",
"For the liver and kidneys that have suffered through my many follies",
"For the bones of my face",
"and my hips",
"and my knees",
"and my feet",
"All without cancer",
"all without cancer",
"Let us pray",
"In a garden",
"there were three thieves",
"The first",
"a young woman",
"fingers like spider legs",
"quick",
"as fog on the sun's first shoulder",
"The second",
"a blind man who found coins with nothing but",
"his nose",
"The third was an old man",
"with eyes",
"that anyone would trust",
"and hands that worked",
"beneath those eyes",
"quickly and without shadow",
"The woman said to the men",
"Listen",
"I hear",
"that the master of this garden is a wicked man",
"who every night takes out his heart",
"polishes away",
"its many blemishes",
"then swallows it whole",
"The heart can take such ruckus because it's made",
"of gold",
"pulse by pulse",
"blond as the noon sun",
"The two men rubbed their hands together",
"for heat and mischief",
"and studied the wall",
"leading into the house",
"their heads stuffed with visions",
"of grappling hooks and such wonderful slinkiness",
"as never occurs in old men",
"Maybe these three overtake the wall",
"and overcome",
"the wicked garden keeper",
"and take for themselves",
"the secret heart",
"but listen",
"to understand",
"this story",
"you need to know that I mean",
"not thieves",
"but the three for whom the Buddha",
"gave up his life",
"and took up the mantle of the dharma",
"one sick",
"one old",
"one dead",
"moving through the street",
"like light on film",
"like dreams",
"There is no garden",
"and these three barely know each other",
"The sick one",
"a nurse who caught her care",
"and for her",
"death is a dark bird that shrugs its shoulders and goes on",
"calling and calling into the red reaches of dusk",
"The old one is a man who lost a wife or son",
"or great fortune - it doesn't really matter",
"But he lost",
"and the gap in his body is a sinkhole",
"into which the universe falls",
"cell by cell",
"mote by mote",
"And the dead one is the only happy one",
"not because",
"he has any true happiness",
"or because he knows",
"anything more than the sick and the old",
"but because",
"at least he got out of this mess",
"and he's no longer",
"the stuff of governments",
"and all the tiny pressing matters",
"is the past",
"less than garden soil or dust",
"Gautama",
"passes in his litter",
"eyes shedding time and its many mistakes",
"and yet he never knows how the old",
"the sick and the dead",
"meet in his wake to play cards in the dark",
"each with a handful of coins",
"and a mouth furred with the murmurs of the shadow life",
"They shuffle",
"and deal",
"raise and fold",
"the betting pile forming a haphazard heart",
"in the gambler's half-light",
"Maybe the dead one notices",
"the flicker of coins on the table",
"and maybe he learns enough",
"what wonders passed him on his funeral day",
"tell the others how the world is not the world",
"but something smaller",
"but listen",
"to understand this story",
"you need to know",
"and three junkies in a room",
"in south Baltimore",
"split by smoke and sunlight",
"There is no garden",
"there is no one to save us or take us home",
"and no one cares",
"for our dreams",
"There is a girl",
"a boy and a man too sick",
"to do anything but get high and lie back and dream of television",
"The boy says to the girl",
"my dad's heart is made of cabbage",
"and one day I will eat it",
"The girl replies",
"I know your dad",
"and his heart is hard and precious",
"and one day maybe",
"you will be lucky enough to steal it and swallow it whole",
"The man",
"laughs in a shudder of chickenwire and stones",
"and none of them loses time or finds a way beyond the walls",
"of the grand and terrible city",
"at least on that day",
"when the heroin is rich and sweet and every vice is cheap",
"as water",
"But listen",
"turn the pages",
"watch the days",
"flip past",
"the sun in its groove",
"the moon in its track",
"The boy",
"loses the girl and buries the man",
"and goes on to see",
"how the world is not the world",
"and how the unseen universe",
"boils up inside us",
"spinning into matter",
"gravity",
"the luminous forces",
"The boy survives",
"gains",
"grows",
"and becomes so wonderfully",
"full of shit",
"each tale tall enough to cradle his inconsolable shadow",
"as gently as an egg in a nest",
"I persist",
"the boy says",
"I'm still here",
"because the heart doesn't die until the fire goes out",
"and the fire goes on as long as the body carries it",
"Because I know this",
"I know you",
"So don't be sad",
"Don't worry",
"Let's go for a walk",
"You are no stranger to me",
"How often have I asked the wind",
"to winnow me down to bone",
"and listened as the stony wind",
"said nothing in return",
"Alone",
"I move along in fog",
"my heart",
"a concrete urn",
"a muffled drum",
"Not even my fragile art",
"can keep me from the rain to come",
"The mountain is silent",
"The pale blue ash",
"still as the stone it will soon become",
"Nothing moves here yet - wind",
"sun",
"even flesh",
"I find the outline of my home - ",
"a bruise in a street-shaped line of bruises - ",
"and marvel bitterly at how the earth",
"takes when it takes",
"how the mountain closes",
"like a jaw on what I’ve made",
"the worth",
"of which is dust",
"But still I return",
"climbing drifts of cooling fire",
"fogged with soot",
"of the underworld",
"lung-black or white as chalk",
"to find among the coals what wouldn’t burn",
"a lock of hair",
"a locket underfoot",
"a ladder leaning down into the dark",
"Because you were alone in your body",
"and could do nothing but cry in your thorns",
"I came to you",
"and spoke to you",
"and sprawled in your lap",
"until you understood that what I held",
"in my throat wasn't thunder",
"but sunlight",
"There was the moment",
"you really knew it",
"felt it erupting",
"beneath your hands like a miniature star",
"but then you looked into my eyes",
"and saw the simplicity of form",
"fur on flesh",
"flesh on bone",
"the body",
"you held like a secret child",
"the smallness of us in the next moment",
"Now that I'm gone",
"you must know",
"that I was never simple",
"that you",
"were never my keeper",
"the body",
"you held was a cradle of stars",
"Everywhere the sunlight is",
"I am",
"Everywhere you are",
"the sunlight is",
"I usher the beetle out",
"gather it in",
"the folds of a notebook",
"and carry it out to the cold",
"where it might live or die",
"according to the weather",
"To any beetle caught in my house",
"I am the weather",
"and doors are how I change",
"the seasons",
"The beetle drops from the pages",
"and into the slender hay-colored leaves",
"of All Saints Night",
"As I write this",
"I wonder",
"if I'm writing about the beetle",
"or tracing its path across the page",
"if this is the beetle's song or mine",
"I took care of the beetle",
"You took care of beauty",
"having heard the story in a different way",
"The beetle was a silhouette",
"in the lampshade",
"a lozenge of shadow",
"in a field of yellow light",
"I wish I could reach into its mouth",
"and take hold of whatever song",
"I found there",
"I close my eyes",
"and see the beetle's",
"gray body dropping into the dark",
"like snow or moonlight",
"May the moon rest its fat snowy paw",
"upon the beetle's shoulder",
"and guide it to another",
"brighter",
"door",
"When I'm lonely",
"I imagine lying in a field of parchment",
"my body burnished by an incandescent sun",
"Sometimes I am a vessel for beauty",
"and sometimes I am what lets beauty",
"go into the night",
"In every beetle is the ticking of clocks",
"breaths between words",
"hinges for shoulders and wings",
"Maybe the beetle closes its eyes",
"and remembers summer",
"the hundred",
"million subtle bodies of love and sunlight",
"a sidelong fumble in the soil",
"when drunk on the juice of my lemon basil",
"I am not sure if the beetle has left the house",
"or if the house has grown to hold the beetle",
"Was the beetle drawn to the lamp",
"or to me",
"Let me burn all night",
"Let me be bright",
"Whatever is drawn to me loves light",
"and everything I love has wings",
"I surrender to the second law of thermodynamics",
"the law of dishes that dirty themselves",
"I surrender",
"to my front door that blows open no matter",
"what I do",
"ensuring I heat the world",
"Every night is the vigil",
"an hour of sleep",
"a few minutes of shivering awake to rise",
"check",
"the latch",
"and shut",
"At midnight",
"I stand",
"in the doorway and turn the handle",
"watching",
"the latch piston in and out",
"At one o'clock",
"I lurch out of bed",
"remembering",
"a dream of a woman I loved",
"doing my dishes",
"At two",
"I wake and feel myself bleeding",
"At three o'clock",
"I dream",
"of a woman in my bed",
"her hands wet",
"I shut",
"the door",
"check the stove",
"and see the clean plates",
"softened with dust",
"At four",
"I dream of myself",
"rising to shut the door",
"and returning to bed to dream",
"of engines",
"At five",
"I dream",
"of engines",
"the house is a series of doors",
"my body",
"pistoning back and forth",
"shutting one door",
"and opening another",
"standing at the sink or falling",
"into bed",
"The bed is its own house",
"visited by women",
"who vanish almost as soon as they appear",
"pistons",
"pumping a stuttering engine",
"My body is an engine",
"that hacks and shudders",
"and I return to it",
"standing",
"at its threshold",
"checking its hinges",
"crossbeams",
"cylinders and fuel",
"then falling into it as I would fall",
"into a woman",
"It's almost dawn",
"The door",
"stands open",
"and the sink is full",
"I surrender",
"to the door",
"Let the heat bleed out and the light pour in",
"Let the town begin",
"Let them return to their bodies and leave",
"to master machines",
"hammer out wonders",
"burn metal underwater",
"trap lightning",
"siphon steel from stone",
"Let them keep vigil",
"over thresholds",
"beating back weeds in the sidewalk",
"dirt in the street",
"the dead in their bodies",
"the cold",
"around and above us",
"The awful space into which",
"we dissipate",
"The dust and gas",
"all the dumb luck",
"The deaf inherit the crickets",
"never knowing",
"they have them",
"night goes on as night",
"and the grass says nothing",
"The blind",
"inherit the movies",
"and the mute receive",
"the kingdom of karaoke",
"the glory and power",
"of the sing-along screen",
"The pious",
"the poor",
"marvel at their bounty of grapefruit knives",
"the dead grit teeth at their gift of the living",
"the warm industrious bodies crowding their cozy tombs",
"Finally",
"the meek inherit the earth",
"the broad unyielding earth",
"the earth",
"which laughs and waves and runs a hand",
"through thick perennial hair",
"then goes on forever without them",
"Your house was the house of someone",
"between lives",
"bags almost packed",
"a train ticket tucked in a sheaf of bills",
"you’d never pay",
"he was your son",
"I was hiss friend",
"and death was quick in your hair",
"each",
"played his part in folding your dresses",
"wrapping your plates in horoscopes",
"and drinking your scotch",
"he moved forward",
"by some quiet plan",
"I moved forward",
"in his shadow",
"and death moved forward",
"saying",
"this and not that",
"here and not there",
"pack the books",
"forget the bills",
"In this way",
"over many nights",
"your house was disassembled",
"the books went into his office",
"the dishes to consignment",
"your body into trees",
"the trees into crossbeams",
"of other houses",
"whose owners sleep in our history",
"of leaves and spirits",
"unsuspecting",
"If all wood",
"woke to previous lives",
"whose hand would you be holding",
"Are you the doorway of a chapel",
"or the ties of a railroad",
"Would you find yourself in my hand",
"crumpled",
"then smoothed out",
"as I write the story",
"of these many days without you",
"I'm drunk and lost in Minneapolis",
"It's last century",
"and my hair is long and you're here somewhere",
"but I can't find my wallet or Aldrich Avenue or",
"anything that looks like Minneapolis",
"because",
"I'm drunk and lost in Los Angeles",
"and I have",
"a crew cut and twenty-five dollars and I've had",
"so much whiskey I can feel the century diminishing",
"you in there somewhere",
"pushing away like a ship from a pier",
"which is why I'm drunk and lost in San Francisco",
"and can't find my hotel which looks like a hotel",
"in New Orleans or Baton Rouge",
"no one will give me",
"any of the holies",
"my America",
"I'm drunk and lost",
"and you're here",
"somewhere",
"with my ring and my memory",
"It's last century",
"or a century ago",
"and I can't remember the shape",
"of your face or the year we met",
"Maybe memory is like",
"a ship that no one captains",
"or a locked box",
"that rattles and rattles but never confesses",
"what it's hiding",
"I wander sidestreets and squares",
"and imagine you asleep in the locked box of your bed",
"your house a ship that always drifts away from me",
"It's New Year's Eve",
"and I'm thirty",
"Times Square",
"is closed",
"I'm lost in a crowd of children and barkers",
"and 42nd Street is full of elephants",
"One of them",
"smaller than the others",
"white as a sail",
"patiently",
"chewing a plait of grass",
"He watches as I fumble forward",
"drunk on champagne",
"and reach out to touch his trunk",
"He's solid as a square-rig mast or an old tree",
"his eyes on my face",
"dark and definite",
"This is Manhattan",
"the eyes say",
"just a city",
"just a girl",
"just America",
"It's not everything",
"Go home",
"On the beach",
"I try to become",
"whatever comes after the body",
"I renounce gin and kissing",
"I renounce",
"grammar",
"The cock and belly",
"conspire to annoy me",
"Lips and commas",
"cleave to me",
"I’m parsed",
"against my will",
"and even the sand",
"insists on being symbolic",
"I would give up",
"and just be flesh again",
"but it’s winter",
"the sun is meek and white",
"and a sleet wind",
"snaps at the pier flags",
"My body tells me that after the body",
"is the body or the body",
"What a crybaby",
"What an ape",
"I is all it can say",
"I",
"I and my body fight",
"I tell it to leave me alone",
"but it carries me everywhere",
"I tell it",
"to let me go",
"but it cleaves",
"I shove it",
"and I fall backwards",
"Together we lie",
"in the sleet sand",
"my body greedily breathing",
"Am I doomed to be a noun",
"The ferry comes",
"gray",
"on the denim-dark water",
"We stand",
"and shake hands",
"A light snow",
"gnaws at the piers",
"and lightly",
"one of us crosses to the deck",
"We wave to each other",
"hands",
"in unison",
"back and forth",
"until",
"the sea is blank again",
"and the snow",
"fills up the space between us",
"like words or flies",
"This is the tree that guards my daughter's",
"body",
"Chokecherry",
"skinny-limbed",
"drizzling",
"tongue-colored fruit",
"I would come here",
"with a bow saw and cut it to kindling",
"if only her hair",
"weren't in the corewood",
"spindled in the hidden",
"vascular spaces",
"I'm even gentle with the fallen",
"fruit",
"careful not to kick aside whatever dream",
"she's lost in",
"though once I ate three chokecherries",
"just to see",
"Dry tart needling roots of teeth",
"throat fisted shut",
"eyes clenched against the gut-rip",
"that doubled me over",
"astonished by the hurt",
"of such a small thing",
"When your mother died",
"we entered her house",
"and emptied each room",
"packing up blankets",
"combs",
"and shoes",
"but throwing out drugs and prescriptions",
"as though she might come back whole",
"I watched",
"as he worked through stacks of bills",
"sorting past due",
"from soon to be past",
"and when the living house",
"nothing but dust",
"we sat on her porch",
"and drank her scotch",
"We drank mechanically",
"like boys",
"performing a chore",
"until the street began to yaw",
"and his face twisted in that chokecherry look",
"and he said",
"at least her hair goes on",
"subterranean",
"lustrous and secret",
"When I lost my daughter",
"I couldn't sob aloud until I understood",
"that grieving isn't eating",
"and if no one ate",
"everyone would die and the world would fill up",
"with hair",
"Nothing threatens us like hair",
"spun",
"from the body's failure",
"ready to strangle roots",
"split streets",
"climb walls",
"choke rivers",
"flood the ocean",
"with braids",
"The porch rocked",
"and I held him as gently as I would hold a child",
"or ashes",
"I tried to embrace everything that swayed",
"this is my brother",
"This is the empty house",
"This",
"the world of hair",
"This is the tree",
"my daughter",
"We left in the morning",
"green and luminous",
"taking nothing with us",
"Our cars idled",
"on the interstate",
"the shoulder littered",
"with watches",
"wallets",
"keys and shoes",
"We tore down fences and cut through fields",
"and when we came to the woods",
"we pulled off our skins and shook out",
"our soft wet fur",
"We ran until the groves",
"gave way to grass",
"stripped down to feathers",
"crowded streams",
"pared our bodies to scales",
"and simple eyes",
"and swam to the ocean",
"The tide scraped away our last bits",
"of rib and jaw until we became",
"living water",
"mitochondrial",
"and language",
"could no longer save us",
"That was when",
"we arrived at the other shore",
"and the angel",
"extinguished her sword",
"cupped us in her hands",
"and took us",
"luminous",
"to her lips",
"Manhattan",
"thirty million yards of cotton",
"denim and leather",
"hiding two million bodies",
"infected with memory",
"pollutes my morning with secrets",
"I learned long ago",
"Manhattan swallowed me in human traffic",
"the press of hands",
"the rush of worlds and things",
"memory is contagion",
"multiplying",
"door handles and subway seats",
"Time is just numbers in a clock",
"not a movement forward or away",
"In the crush of a crowded train",
"every living past becomes now",
"wars overlap",
"the news is forever new",
"faces jitter from young to old",
"and back",
"and the car fills with ghosts of children",
"brothers and sons long vanished from everyone",
"but me",
"It took me years to mute the remembered world",
"everyone knows someone's listening",
"Listen",
"Don’t leave me",
"Just listen",
"They’re thinking",
"Oh yes",
"This is the world",
"this is my body in the world and how did I get here",
"How much does this cost",
"how much do I know and what if no one believes",
"Believe me",
"There is so much to listen for",
"so much world and so little body",
"such a great cost",
"I’m lonely",
"not yet",
"I could have been the sideshow that ran the carnival",
"the missing and the dead",
"being freakish bores me",
"the city vibrates with tortures and murders",
"everyone but the city has forgotten",
"So",
"I hold",
"tell their secrets back to them",
"they sit there blinking",
"infants discovering their reflections",
"Sometimes I wish",
"I were speaking",
"it’s enough to know",
"I only have to listen to one person",
"one pair of hands in mine",
"I can listen deeply",
"see your daughter’s face",
"taste the salt of what you’ve lost",
"find the part of you that sings",
"I can reach across these universes",
"find your hand",
"step back",
"into the body I knew when I left you",
"my hair to my chest and yours to your waist",
"our pockets packed again with loose change",
"and good tobacco",
"In that other life",
"we've grown neither up nor old",
"I am untested",
"by the trials of Spenser and Milton",
"and you still have baker's hands",
"those wounded ropes",
"of wrist that all night drove dough from board",
"to bread",
"I can learn the hundred million",
"points of difference",
"tiny gestures",
"of my other self",
"that simpler animal",
"who settles in with cheap coffee",
"rolls",
"a cigarette",
"and contemplates the growing snow",
"with a shrug or a shiver",
"his body wearing",
"your odor like a coat",
"wheat",
"honey",
"myrrh",
"In that universe of unrelenting youth",
"shoulders forever burnished",
"sickness a myth",
"of some dimly imagined life",
"the lines",
"don’t gather on my face like frost",
"on glass",
"and your body doesn’t begin to stutter",
"In this life",
"cancer",
"it took a year to winnow out",
"cost you",
"your hair and a little life",
"I imagine you",
"withered",
"worn to sinew",
"you're still the soft strong bronze I knew",
"So many things have happened in this one of many worlds",
"knots that I might tighten or unwind",
"if I had the choice",
"universes close to us",
"garden paths we never took",
"the future laid out like a highway with many tolls",
"many lanes in one direction",
"no exits",
"By the time you read this",
"I imagine I'll be ocean",
"I've been adrift for several days",
"and my skin is the color of salmon",
"The sun's brass pistons beat the waves",
"until they glitter like chandeliers",
"and my eyes are the color of salt",
"I dream of water and wake to water",
"and hate water and want it",
"fresh",
"clean",
"smelling of cities",
"And my voice is the color of the weed-roped sea",
"This is a note for you my Emma",
"who never learned to read",
"I drove sixty miles to see the beach",
"in winter",
"I crouched at the water line",
"alone",
"The sand",
"full of living things",
"hermit crabs",
"burrowers",
"breathers",
"You would have loved",
"the bubbles that rose from the wet sand",
"almost like soda bubbles",
"steady",
"insistent",
"I crouched",
"I wrote this note",
"We drown",
"burrow",
"breathe",
"persist",
"We go on without meaning to",
"and I am thirteen today",
"I am so lonely and no one",
"talk to me",
"I hope you will be my friend",
"I have been alone a long time",
"and my mouth is the color of silt",
"I've survived by breathing",
"into a bottle and drinking the condensation",
"a foul warm trickle of air",
"The boat",
"rocks and tumbles",
"and the sea won't stop",
"winking and winking",
"a rolling white desert",
"of water",
"I have been lost at sea",
"a countable number of days",
"but numbers",
"have been burned from my brain",
"integers",
"dissolving to irrational numbers",
"and then to decimals",
"lone",
"spinning",
"around me like flies",
"The only number remaining",
"is one",
"one me",
"one lifeboat",
"one ocean",
"Everything condenses to one",
"It's a foul trickle",
"of certainty",
"by the time you read this",
"I won't be able to say",
"There were no survivors",
"but me",
"I won't be able to say a thing",
"my mouth",
"sealed by salt",
"my slug tongue a sliver of bait",
"You will speak for me",
"You will say",
"There were no survivors",
"you are never tired",
"Nightly your ghost",
"lies like a breathing stone in my arms",
"and you cry for another story",
"one more",
"before your infinite sleep",
"So",
"once there was a girl who was never born",
"And her father who was never a father",
"wept at the sight of all that absence",
"and he named the absence and held it",
"like a breathing stone in his arms",
"He wept and wept",
"and then he went",
"to the ocean",
"because he believed",
"that only the ocean could weep as much",
"My sister likes big tall boys",
"with sideburns and spikey hair",
"and skin the color of giraffes",
"she says 'the bigger and stronger the better'",
"and whenever she says this",
"she twirls her hair around her finger",
"and tries to look like a model",
"but boys are so small and weak",
"Ocean",
"I don't know who could be",
"bigger and stronger than you",
"One sun one moon one vaulted sky",
"veiled only by a tentative wisp of clouds",
"(which are one cloud",
"faceted",
"half hidden",
"forming the limitless country",
"of air) and one sea speaking for all",
"chanting over and over again",
"Roll",
"Listen closely and you'll hear",
"in breakers and at shores",
"the sea's chant lengthened - ",
"it says",
"Roll into me",
"The sea is predatory",
"feral",
"consuming all",
"I burn with salt",
"and white noise",
"my body reduced",
"to rigging of tendon and clapboard bone",
"I am one mariner wasting in one ocean",
"under one moon one sun",
"and soon the starved clay of my face",
"will collapse and roll into the ocean",
"and the country of air will rain down",
"into these waves",
"and the sun",
"will flicker and tumble down",
"and the moon",
"will careen into the Atlantic",
"And then",
"there will be only the weed-roped sea",
"chanting to itself",
"Roll into me",
"It's winter",
"a season I imagine",
"you'd love",
"I imagine too much",
"I imagine your hands",
"so small",
"I could surround them with a finger",
"and carnivals",
"braids",
"makeup",
"ear infections",
"photographs",
"arguments",
"sundresses",
"piano lessons",
"days",
"upon days upon days upon days",
"Not knowing your face",
"not knowing",
"even the sound of your breath",
"I cannot say that I loved you",
"with the roots of my teeth",
"with the cords of my throat",
"and my long wet wings of lung",
"But I can tell you what I know",
"I drove sixty miles in winter",
"to discover that you are simply my ocean",
"in the shape of a little girl",
"Once there was a man so burrowed",
"imagining became remembering",
"This man",
"this father who was never a father",
"He wrote a note to his daughter's ghost",
"and threw it into the sea",
"And what happened next",
"I don't know",
"I only know that we go on",
"that we must",
"that days and days await us",
"I will come back one day",
"and I will marry you",
"and there will be mermaids and flowers",
"and mermen with steel guitars",
"and my sister will be jealous",
"and my mother will be proud",
"and seahorses will carry me to your house",
"and we'll live down there in all those",
"secret weedy valleys",
"and the sun will come through the water",
"like sequins or gold coins",
"I'll forgive you",
"for all the sailors and swimmers",
"I'll forgive you for eating boats and children",
"for sharks and big octopuses and stuff",
"but you have to forgive me",
"for drowning with you",
"because I'm only arms and legs and lungs",
"and I'll drown   but I want to",
"you are that beautiful",
"Everywhere you walk is white",
"and white the sky",
"and the warm dusty bloom",
"of your breath",
"Only the branches",
"dark enough to stand against the pale",
"shouldering snow",
"nodding to the wind",
"the bitter cant",
"Wherever you go",
"may you be like the branches",
"dark",
"against the pale",
"dark ropes of earth",
"packed with the language of green",
"On foot in the city you become",
"the city",
"ancient and new",
"swimming",
"in the fanged heat of another July",
"First are the pawn shops",
"block after block",
"of barred doors",
"and men young and old hanging",
"on street corners with nothing to do",
"Some",
"wait for buses and others just wait",
"heads full",
"jazz",
"elevator song",
"anxious calculations for utility bills",
"silent rehearsals for food stamp lines",
"and welfare lines",
"You remember yourself",
"as a citizen of this world",
"years ago",
"in a city in California",
"when you walked two miles from a bread line",
"to your dive apartment with fifty pounds",
"of beans and rice",
"That ache is still alive",
"in your shoulders",
"and you carry it",
"with timid pride into the next neighborhood",
"a world where everyone is tasteful and owns",
"a duvet",
"and the sidewalk furniture",
"of sunny cafes is all immaculate",
"wicker and wood",
"A woman smiles and says",
"hello to you",
"blithe and elegant",
"and you think of that afternoon in Baltimore",
"when a woman stopped to ask if you were all right",
"because you were at the grave of a poet",
"in a bad part of the city",
"You wonder",
"there are only so many types",
"of people",
"repeating and repeating",
"through all cities and every vessel of life",
"but you only need to talk to one stranger",
"to remember how everyone is rich",
"and strange",
"The neighborhood of Russian Jews",
"and its odor of fresh bread",
"like sweet earth",
"The neighborhood of dive bars and Asian",
"groceries",
"The many tiny Americas",
"that make up the ancient city",
"Farther",
"into this cobblestone belly",
"where markers",
"of the Revolution lay",
"where the underground",
"railroad kept its many stations",
"A house",
"with a band practicing",
"loud and messy",
"luminous tin of drums and guitars",
"and you can almost feel the years peel away",
"your hair past your shoulders",
"a beer in your hand",
"your friends not yet heavy and lovely",
"with children",
"A man with boots just like",
"the ones you owned",
"back in the day",
"A pair of hips",
"a face that could be her face",
"Watch",
"as they pass you",
"turn the corner",
"and walk down",
"into some history you don’t yet know",
"commending themselves with each step",
"to historians and librarians who fold them",
"into the dream of the republic",
"Maybe",
"you’ll see them again",
"in some avenue",
"of footnotes",
"some station of antiquity",
"all of you gathered by the scholar’s hand",
"and waiting to journey to whatever",
"corner of the record belongs to you",
"They’ll shake your hand and ask",
"Who are you",
"To each of them",
"say",
"I’m the one who saw you",
"I’m the one they quoted",
"the anonymous",
"the bystander without a name",
"Dear traveler",
"dear reader",
"remember me"
 ];

function buildTweet(myArray){
   var phrases = [];

   while ( (phrases.join('\n')).length <= 140 && phrases.length < 3 ){
     phrases.push(chooseRandom(myArray));
     var srch = new RegExp('^(and |or |but |into |of )', 'i');
     var lastkey = phrases.length-1;

     if ( lastkey === 0 && phrases[lastkey].search(srch) !== -1){
          phrases[lastkey] = phrases[lastkey].replace(srch,'');
     }
   }

   if ( (phrases.join('\n')).length > 140 ){
     phrases.splice(phrases[phrases.length-1],1);
   }
   phrase = phrases.join('\n');
   return phrase;
}

function chooseRandom(myArray) {
 return myArray[Math.floor(Math.random() * myArray.length)].toLowerCase();
}

var phrase = buildTweet(phraseArray);
//console.log(phrase);

Bot.tweet(phrase);

